annotations:
  max_scale_version: 24.04.1
  min_scale_version: 24.04.0
  truecharts.org/SCALE-support: "true"
  truecharts.org/category: media
  truecharts.org/max_helm_version: 3.14
  truecharts.org/min_helm_version: 3.11
  truecharts.org/train: incubator
apiVersion: v2
appVersion: 1.4.2
dependencies:
  - name: common
    version: 23.0.0
    repository: oci://tccr.io/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
  - name: redis
    version: 14.0.5
    repository: oci://tccr.io/truecharts
    condition: redis.enabled
    alias: ""
    tags: []
    import-values: []
deprecated: false
description: Simple and effective tool for measuring ISP performance at home
home: https://itconstruct.com.au/coding_projects/
icon: https://itconstruct.com.au/coding_projects/netprobe_lite.webp
keywords:
  - photos
kubeVersion: "=1.26.6-0"
maintainers:
  - name: TrueCharts
    email: info@truecharts.org
    url: https://truecharts.org
name: netprobe_lite
sources:
  - https://github.com/plaintextpackets/netprobe_lite
  - https://hub.docker.com/r/plaintextpackets/netprobe
type: application
version: 1.4.2
